- RelhaxModpack/RelhaxModpack/App.xaml
- RelhaxModpack/RelhaxModpack/UIComponents/FirstLoadAknowledgements.xaml
- RelhaxModpack/RelhaxModpack/UIComponents/FirstLoadAknowledgements.xaml.cs
- RelhaxModpack/RelhaxModpack/UIComponents/NewsViewer.xaml
- RelhaxModpack/RelhaxModpack/UIComponents/NewsViewer.xaml.cs
- RelhaxModpack/RelhaxModpack/UIComponents/VersionInfo.xaml.cs
Added windows for license agreement (and acknowledgement about our services) and a news viewing window, to see the changes in the database and application for the end user.
> Relhax v2 eula news

- RelhaxModpack/RelhaxModpack/MainWindow.xaml
- RelhaxModpack/RelhaxModpack/Windows/AdvancedProgress.xaml
- RelhaxModpack/RelhaxModpack/Windows/CreateFTPFolderName.xaml
- RelhaxModpack/RelhaxModpack/Windows/DatabaseEditor.xaml
- RelhaxModpack/RelhaxModpack/Windows/DatabaseEditorDownload.xaml
- RelhaxModpack/RelhaxModpack/Windows/DeleteOldCache.xaml
- RelhaxModpack/RelhaxModpack/Windows/DeveloperSelectionsViewer.xaml
- RelhaxModpack/RelhaxModpack/Windows/Diagnostics.xaml
- RelhaxModpack/RelhaxModpack/Windows/EditorAddRemove.xaml
- RelhaxModpack/RelhaxModpack/Windows/EditorSelectMediaUploadLocation.xaml
- RelhaxModpack/RelhaxModpack/Windows/FirstLoadAknowledgements.xaml
- RelhaxModpack/RelhaxModpack/Windows/GenericYesNoWindow.xaml
- RelhaxModpack/RelhaxModpack/Windows/InstallFinished.xaml
- RelhaxModpack/RelhaxModpack/Windows/NewsViewer.xaml
- RelhaxModpack/RelhaxModpack/Windows/PatchTester.xaml
- RelhaxModpack/RelhaxModpack/Windows/Preview.xaml
- RelhaxModpack/RelhaxModpack/Windows/ProgressIndicator.xaml
- RelhaxModpack/RelhaxModpack/Windows/VersionInfo.xaml
getting the changes before I delete the branch
> Relhax v2 tags

- RelhaxModpack/RelhaxModpack/Utils/Translations.cs
Full spanish translation plus a couple more details
> Spanish translation

- RelhaxModpack/RelhaxModpack/Utils/Translations.cs
Also fixed some typos in English strings.
> Updated RU strings

- RelhaxModpack/RelhaxModpack/Utils/Translations.cs
Finally, hope i didn't fail anything !
> Translations.cs FRENCH VERSION

- RelhaxModpack/RelhaxModpack/InstallerComponents/InstallEngine.cs
- RelhaxModpack/RelhaxModpack/Utils/Translations.cs
Added what's missing, fixed what's wrong, redone a lot.
Plus minor typos for other languages.
I hope I did not screw up with the merges, so double check me ;)
> Polish translation

- RelhaxModpack/RelhaxModpack/Utils/Translations.cs
- RelhaxModpack/RelhaxModpack/Windows/GameCenterUpdateDownloader.xaml
This time I tried to organize changes better within the commits.
In general I tried to reference more translation keys, so we don't have one simple button or phrase translated a dozen of times.
DrWeb may want to take a look at `PreviewNextPicButton` and `PreviewPreviousPicButton`, he voiced some opinions about those being pulled directly from `next` and `previous`.
> Null's Best: Clean up, experiments and organized chaos.

- RelhaxModpack/RelhaxModpack/Utils/Translations.cs
Hello there. I heard you like dem PRs.
> GER forum button fixes for PL and RU.

- RelhaxModpack/RelhaxModpack/Utils/Translations.cs
Some small spanish translation fixes and rewordings
> Spanish translations fixes

- RelhaxModpack/RelhaxModpack/Utils/Translations.cs
Plus fix a double exclamation mark for ``creditsUsersLikeU`` in RU;
Did I mention how much I love hard-coded punctuation? ❤️ 
Regarding the credits button, have mercy. I can't come with anything better than that :D
> PL Credits translation; PL package markers translation;

- RelhaxModpack/RelhaxModpack/Windows/DatabaseEditor.xaml
> Add new links for database standards, and small edits to text

- RelhaxModpack/RelhaxModpack/Utils/Translations.cs
Added translation for "moveAppOutOfDownloads" and "selectionFormatOldV2" lines.
Also fixed "and and" in English string for "moveAppOutOfDownloads".
> Updating localization package: applying updates

- RelhaxModpack/RelhaxModpack/Windows/DatabaseEditorDownload.xaml.cs
Yup, the title says it all. Was a pretty hard change. Took me a while.
> cancel button now closes download/upload window

- RelhaxModpack/RelhaxModpack/Common/Translations.cs
Poor @SigmaTel71 being ignored on the channel 😞
> 100% translation coverage :D

- RelhaxModpack/RelhaxModpack/Common/Translations.cs
Still fresh! Smell them hot western-slavic letters! ``ĘÓĄŚŁŻŹĆŃ`` 😄
> Update PL translations for 1.3.1.0;

- RelhaxModpack/RelhaxModpack/MainWindow.xaml
- RelhaxModpack/RelhaxModpack/Translations/Translations.cs
- RelhaxModpack/RelhaxModpack/Translations/TranslationsEnglish.cs
- RelhaxModpack/RelhaxModpack/Translations/TranslationsFrench.cs
- RelhaxModpack/RelhaxModpack/Translations/TranslationsGerman.cs
- RelhaxModpack/RelhaxModpack/Translations/TranslationsPolish.cs
- RelhaxModpack/RelhaxModpack/Translations/TranslationsRussian.cs
- RelhaxModpack/RelhaxModpack/Translations/TranslationsSpanish.cs
- RelhaxModpack/RelhaxModpack/Windows/VersionInfo.xaml
What is your Copy/Paste WN8? 🤣
```
2021-06-29 12:58:30.179   ERROR: Translation SelectionDefaultText does not exist in any languages
2021-06-29 12:58:30.179   ERROR: Translation EnableBordersDefaultV2Text does not exist in any languages
2021-06-29 12:58:30.179   ERROR: Translation BackupModsText does not exist in any languages
2021-06-29 12:58:30.179   ERROR: Translation BackupModsSizeLabelUsed does not exist in any languages
2021-06-29 12:58:30.179   ERROR: Translation SaveDisabledModsInSelectionText does not exist in any languages
2021-06-29 12:58:31.582   ERROR: Translation BackupModsSizeLabelUsed does not exist in any languages
2021-06-29 12:58:33.765   ERROR: Translation SelectionDefaultText does not exist in any languages
2021-06-29 12:58:33.765   ERROR: Translation …
```
> Fixed a full Maus of missing translations in 1.3.2.8;

- RelhaxModpack/RelhaxModpack/Translations/TranslationsPolish.cs
So, what is the running joke? :D
> Add missing PL Lauch... strings

- RelhaxModpack/RelhaxModpack/Translations/TranslationsFrench.cs
- RelhaxModpack/RelhaxModpack/Translations/TranslationsGerman.cs
- RelhaxModpack/RelhaxModpack/Translations/TranslationsPolish.cs
- RelhaxModpack/RelhaxModpack/Translations/TranslationsRussian.cs
- RelhaxModpack/RelhaxModpack/Translations/TranslationsSpanish.cs
> Fix missing ``BackupModsSizeLabelUsedDescription`` for all the locales;

- README.md
- RelhaxModpack/RelhaxModpack/Translations/TranslationsPolish.cs
You have selected "Listen to your heart", but it conflicts with the following package(s):
- Display Expectations, of category Society
- Basic Logic, of category Brain
We cannot resolve this conflict, you have no option.
😢
> PL translation of ``Conflicting Packages Dialog``

- RelhaxModpack/RelhaxModpack/Translations/TranslationsPolish.cs
How come I did not see those when sober, but now, after a few beers my spider sense kicked in...
I see the PR went without you catching it. Trust no one! :P
Now it works, at least it compiles.
> PL translation FIX (critical).
